# Generated by Django 6.0.5 on 2026-05-19 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _create_profiles_for_existing_users(apps, schema_editor):
    User = apps.get_model("auth", "User")
    UserProfile = apps.get_model("accounts", "UserProfile")
    for user in User.objects.all().iterator():
        UserProfile.objects.get_or_create(user=user)


def _noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_platform_formateur",
                    models.BooleanField(
                        default=False,
                        help_text="Si coché, l’utilisateur accède à « Espace formateur » sur le site public "
                        "(catégories, sujets PDF, examens, corrections, demandes d’abonnement, récap.) "
                        "sans être obligatoirement staff Django.",
                        verbose_name="formateur plateforme (contenu & abonnements)",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "profil utilisateur",
                "verbose_name_plural": "profils utilisateur",
            },
        ),
        migrations.RunPython(_create_profiles_for_existing_users, _noop_reverse),
    ]
