# Generated by Django 6.0.5 on 2026-05-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_content_formateur',
            field=models.BooleanField(default=False, help_text='Accès à « Espace formateur contenu » : catégories, sujets PDF, corrections, examens et récap abonnements — sans validation des demandes d’abonnement.', verbose_name='formateur contenu (sans demandes d’abonnement)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_platform_formateur',
            field=models.BooleanField(default=False, help_text='Accès à « Espace formateur » : contenu, demandes d’abonnement et récap. Incompatible avec le rôle « formateur contenu seul » (choisir l’un ou l’autre).', verbose_name='formateur plateforme (contenu & abonnements)'),
        ),
    ]
