# Generated by Django 6.0.5 on 2026-05-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userprofile_is_content_formateur_and_more"),
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                help_text=(
                    "Limite l’espace formateur à ces catégories (contenu, abonnements, récap). "
                    "Obligatoire pour un formateur non personnel : sans catégorie assignée, "
                    "aucun accès aux données par catégorie."
                ),
                related_name="formateurs",
                to="courses.category",
                verbose_name="catégories assignées",
            ),
        ),
    ]
