# Generated by Django 6.0.5 on 2026-05-14 16:42

import courses.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "billing_period",
                    models.CharField(
                        choices=[("monthly", "Mensuel"), ("yearly", "Annuel")],
                        max_length=20,
                        unique=True,
                        verbose_name="période",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="montant (FCFA ou devise locale)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="actif")),
            ],
            options={
                "verbose_name": "option d’abonnement",
                "verbose_name_plural": "options d’abonnement",
                "ordering": ["billing_period"],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente de validation"),
                            ("approved", "Approuvée"),
                            ("rejected", "Refusée"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="statut",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="demandé le"),
                ),
                (
                    "decided_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="traité le"
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subscription_requests_reviewed",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="décideur",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requests",
                        to="courses.subscriptionplan",
                        verbose_name="formule",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="candidat",
                    ),
                ),
            ],
            options={
                "verbose_name": "demande d’abonnement",
                "verbose_name_plural": "demandes d’abonnement",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valid_until", models.DateTimeField(verbose_name="valide jusqu’au")),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="mis à jour le"),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="active_grants",
                        to="courses.subscriptionplan",
                        verbose_name="dernière formule",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription_access",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "abonnement actif",
                "verbose_name_plural": "abonnements actifs",
            },
        ),
        migrations.CreateModel(
            name="MonthlyCourseContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField(verbose_name="année")),
                ("month", models.PositiveIntegerField(verbose_name="mois")),
                (
                    "pdf",
                    models.FileField(
                        upload_to=courses.models.monthly_pdf_upload_to,
                        validators=[
                            django.core.validators.FileExtensionValidator(["pdf"])
                        ],
                        verbose_name="fichier PDF",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="titre affiché"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_contents",
                        to="courses.category",
                        verbose_name="catégorie",
                    ),
                ),
            ],
            options={
                "verbose_name": "contenu mensuel (PDF)",
                "verbose_name_plural": "contenus mensuels (PDF)",
                "ordering": ["-year", "-month", "category__name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("category", "year", "month"),
                        name="unique_monthly_content_category_period",
                    )
                ],
            },
        ),
    ]
