# Generated by Django 6.0.5 on 2026-05-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_subscription_and_monthly_pdf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlycoursecontent',
            options={'ordering': ['-year', '-month', 'category__name', 'id'], 'verbose_name': 'contenu mensuel (PDF)', 'verbose_name_plural': 'contenus mensuels (PDF)'},
        ),
        migrations.RemoveConstraint(
            model_name='monthlycoursecontent',
            name='unique_monthly_content_category_period',
        ),
        migrations.AlterField(
            model_name='monthlycoursecontent',
            name='month',
            field=models.PositiveIntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], verbose_name='mois'),
        ),
    ]
