# Generated by Django 6.0.5 on 2026-05-14 17:39

import courses.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_monthly_pdf_multiple_per_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='année')),
                ('month', models.PositiveIntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], verbose_name='mois')),
                ('pdf', models.FileField(upload_to=courses.models.correction_pdf_upload_to, validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='fichier PDF (correction)')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='titre affiché')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_corrections', to='courses.category', verbose_name='catégorie')),
            ],
            options={
                'verbose_name': 'correction mensuelle (PDF)',
                'verbose_name_plural': 'corrections mensuelles (PDF)',
                'ordering': ['-year', '-month', 'category__name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CorrectionQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='titre du quiz')),
                ('import_csv', models.FileField(blank=True, help_text='Tableur exporté en CSV : colonnes propositions + colonne « réponses » (indices 1,2,3… ou lettres A,B… ; plusieurs bonnes réponses : 1,3 ou A,C). Voir l’aide dans l’administration après enregistrement.', null=True, upload_to='quiz_imports/', validators=[django.core.validators.FileExtensionValidator(['csv'])], verbose_name='importer un quiz (CSV)')),
                ('correction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='courses.monthlycorrection', verbose_name='correction')),
            ],
            options={
                'verbose_name': 'quiz de correction',
                'verbose_name_plural': 'quiz de correction',
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordre')),
                ('prompt', models.TextField(verbose_name='énoncé')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.correctionquiz', verbose_name='quiz')),
            ],
            options={
                'verbose_name': 'question',
                'verbose_name_plural': 'questions',
                'ordering': ['quiz', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuizOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordre')),
                ('text', models.CharField(max_length=500, verbose_name='texte')),
                ('is_correct', models.BooleanField(default=False, verbose_name='bonne réponse')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='courses.quizquestion', verbose_name='question')),
            ],
            options={
                'verbose_name': 'proposition',
                'verbose_name_plural': 'propositions',
                'ordering': ['question', 'order', 'id'],
            },
        ),
    ]
