# Generated by Django 6.0.5 on 2026-05-14 17:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_corrections_and_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='correctionquiz',
            name='quiz_last_built_for_pdf_key',
            field=models.CharField(blank=True, editable=False, help_text='Technique : évite de relire le PDF à chaque enregistrement. Une action admin permet de forcer une nouvelle lecture.', max_length=500, verbose_name='clé du dernier PDF utilisé pour le quiz'),
        ),
        migrations.AlterField(
            model_name='correctionquiz',
            name='import_csv',
            field=models.FileField(blank=True, help_text='Optionnel si le PDF ne contient pas de tableau détectable. Même structure : colonnes propositions + colonne « réponses » (indices 1,2,3… ou A,B… ; plusieurs : 1,3).', null=True, upload_to='quiz_imports/', validators=[django.core.validators.FileExtensionValidator(['csv'])], verbose_name='import CSV (secours)'),
        ),
    ]
