# Generated by Django 6.0.5 on 2026-05-14 18:30

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_quiz_pdf_sync_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correctionquiz',
            name='import_csv',
            field=models.FileField(blank=True, help_text='Optionnel si le PDF ne contient pas de tableau détectable. Même structure : colonnes propositions + colonne « réponses » (indices 1,2,3… ou A,B… ; plusieurs : 1,3).', null=True, upload_to='quiz_imports/', validators=[courses.models.validate_quiz_import_csv_file], verbose_name='import CSV (secours)'),
        ),
    ]
