# Generated by Django 6.0.4 on 2026-05-15 17:25

import courses.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_quiz_import_csv_validator'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='titre du quiz')),
                ('quiz_last_built_for_pdf_key', models.CharField(blank=True, editable=False, help_text='Technique : évite de relire le PDF à chaque enregistrement.', max_length=500, verbose_name='clé du dernier PDF utilisé pour le quiz')),
                ('import_csv', models.FileField(blank=True, help_text='Optionnel si le PDF ne contient pas de tableau détectable. Même structure : colonnes propositions + colonne « réponses » (A, B, AB, etc.).', null=True, upload_to='quiz_imports/exams/', validators=[courses.models.validate_exam_quiz_import_csv_file], verbose_name='import CSV (secours)')),
            ],
            options={
                'verbose_name': 'quiz d’examen',
                'verbose_name_plural': 'quiz d’examen',
            },
        ),
        migrations.CreateModel(
            name='ExamQuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordre')),
                ('prompt', models.TextField(verbose_name='énoncé')),
                ('exam_quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.examquiz', verbose_name='quiz')),
            ],
            options={
                'verbose_name': 'question (examen)',
                'verbose_name_plural': 'questions (examen)',
                'ordering': ['exam_quiz', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExamQuizOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordre')),
                ('text', models.CharField(max_length=500, verbose_name='texte')),
                ('is_correct', models.BooleanField(default=False, verbose_name='bonne réponse')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='courses.examquizquestion', verbose_name='question')),
            ],
            options={
                'verbose_name': 'proposition (examen)',
                'verbose_name_plural': 'propositions (examen)',
                'ordering': ['question', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='année')),
                ('month', models.PositiveIntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], verbose_name='mois')),
                ('pdf', models.FileField(upload_to=courses.models.exam_pdf_upload_to, validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='fichier PDF (examen)')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='titre affiché')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_exams', to='courses.category', verbose_name='catégorie')),
            ],
            options={
                'verbose_name': 'examen mensuel (PDF)',
                'verbose_name_plural': 'examens mensuels (PDF)',
                'ordering': ['-year', '-month', 'category__name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='examquiz',
            name='exam',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='courses.monthlyexam', verbose_name='examen'),
        ),
    ]
