from django.urls import path

from . import formateur_views
from . import views

app_name = "courses"

urlpatterns = [
    path("", views.home, name="home"),
    path("categorie/<slug:slug>/mois/", views.category_months, name="category_months"),
    path(
        "categorie/<slug:slug>/<int:year>/<int:month>/",
        views.category_month_detail,
        name="category_month_detail",
    ),
    path("categorie/<slug:slug>/corrections/", views.category_corrections, name="category_corrections"),
    path("categorie/<slug:slug>/examens/", views.category_exams, name="category_exams"),
    path(
        "categorie/<slug:category_slug>/<int:year>/<int:month>/correction/<int:pk>/",
        views.correction_detail,
        name="correction_detail",
    ),
    path(
        "categorie/<slug:category_slug>/<int:year>/<int:month>/correction/<int:pk>/pdf/",
        views.correction_pdf_inline,
        name="correction_pdf_inline",
    ),
    path(
        "categorie/<slug:category_slug>/<int:year>/<int:month>/correction/<int:pk>/telecharger/",
        views.correction_pdf_download,
        name="correction_pdf_download",
    ),
    path(
        "categorie/<slug:category_slug>/<int:year>/<int:month>/correction/<int:pk>/quiz/",
        views.correction_quiz,
        name="correction_quiz",
    ),
    path(
        "categorie/<slug:category_slug>/<int:year>/<int:month>/examen/<int:pk>/",
        views.exam_detail,
        name="exam_detail",
    ),
    path(
        "categorie/<slug:category_slug>/<int:year>/<int:month>/examen/<int:pk>/telecharger/",
        views.exam_pdf_download,
        name="exam_pdf_download",
    ),
    path(
        "categorie/<slug:category_slug>/<int:year>/<int:month>/examen/<int:pk>/quiz/",
        views.exam_quiz,
        name="exam_quiz",
    ),
    path(
        "categorie/<slug:category_slug>/<int:year>/<int:month>/<int:pk>/",
        views.monthly_content,
        name="monthly_content",
    ),
    path(
        "categorie/<slug:category_slug>/<int:year>/<int:month>/<int:pk>/pdf/",
        views.monthly_pdf_inline,
        name="monthly_pdf_inline",
    ),
    path(
        "categorie/<slug:category_slug>/<int:year>/<int:month>/<int:pk>/telecharger/",
        views.monthly_pdf_download,
        name="monthly_pdf_download",
    ),
    path("abonnement/", views.subscribe, name="subscribe"),
    path("mon-abonnement/", views.my_subscription, name="my_subscription"),
    path("catalogue/", views.course_list, name="course_list"),
    path("cours/<slug:slug>/", views.course_detail, name="course_detail"),
    path("cours/<slug:slug>/sinscrire/", views.enroll, name="enroll"),
    path("cours/<slug:course_slug>/lecon/<int:pk>/", views.lesson_detail, name="lesson_detail"),
    path(
        "cours/<slug:course_slug>/lecon/<int:pk>/terminer/",
        views.mark_lesson_complete,
        name="mark_lesson_complete",
    ),
    path("mon-apprentissage/", views.my_learning, name="my_learning"),
    path("mes-cours/", views.my_teaching, name="my_teaching"),
    path("formateur/nouveau-cours/", views.course_create, name="course_create"),
    path("formateur/cours/<slug:slug>/modifier/", views.course_edit, name="course_edit"),
    path("formateur/cours/<slug:course_slug>/lecon/nouvelle/", views.lesson_create, name="lesson_create"),
    path(
        "formateur/cours/<slug:course_slug>/lecon/<int:pk>/modifier/",
        views.lesson_edit,
        name="lesson_edit",
    ),
    # --- Espace formateur plateforme (contenu & abonnements) ---
    path("espace-formateur/", formateur_views.formateur_dashboard, name="formateur_dashboard"),
    path("espace-formateur/categories/", formateur_views.formateur_category_list, name="formateur_category_list"),
    path(
        "espace-formateur/categories/nouvelle/",
        formateur_views.formateur_category_create,
        name="formateur_category_create",
    ),
    path(
        "espace-formateur/categories/<int:pk>/modifier/",
        formateur_views.formateur_category_edit,
        name="formateur_category_edit",
    ),
    path(
        "espace-formateur/categories/<int:pk>/supprimer/",
        formateur_views.formateur_category_delete,
        name="formateur_category_delete",
    ),
    path(
        "espace-formateur/sujets-pdf/",
        formateur_views.formateur_monthly_content_list,
        name="formateur_monthly_content_list",
    ),
    path(
        "espace-formateur/sujets-pdf/nouveau/",
        formateur_views.formateur_monthly_content_create,
        name="formateur_monthly_content_create",
    ),
    path(
        "espace-formateur/sujets-pdf/<int:pk>/modifier/",
        formateur_views.formateur_monthly_content_edit,
        name="formateur_monthly_content_edit",
    ),
    path(
        "espace-formateur/sujets-pdf/<int:pk>/supprimer/",
        formateur_views.formateur_monthly_content_delete,
        name="formateur_monthly_content_delete",
    ),
    path(
        "espace-formateur/corrections/",
        formateur_views.formateur_correction_list,
        name="formateur_correction_list",
    ),
    path(
        "espace-formateur/corrections/nouvelle/",
        formateur_views.formateur_correction_create,
        name="formateur_correction_create",
    ),
    path(
        "espace-formateur/corrections/<int:pk>/modifier/",
        formateur_views.formateur_correction_edit,
        name="formateur_correction_edit",
    ),
    path(
        "espace-formateur/corrections/<int:pk>/supprimer/",
        formateur_views.formateur_correction_delete,
        name="formateur_correction_delete",
    ),
    path("espace-formateur/examens/", formateur_views.formateur_exam_list, name="formateur_exam_list"),
    path(
        "espace-formateur/examens/nouveau/",
        formateur_views.formateur_exam_create,
        name="formateur_exam_create",
    ),
    path(
        "espace-formateur/examens/<int:pk>/modifier/",
        formateur_views.formateur_exam_edit,
        name="formateur_exam_edit",
    ),
    path(
        "espace-formateur/examens/<int:pk>/supprimer/",
        formateur_views.formateur_exam_delete,
        name="formateur_exam_delete",
    ),
    path(
        "espace-formateur/examens/<int:pk>/export-resultats.xlsx",
        formateur_views.formateur_exam_results_export,
        name="formateur_exam_results_export",
    ),
    path(
        "espace-formateur/abonnements/",
        formateur_views.formateur_subscription_list,
        name="formateur_subscription_list",
    ),
    path(
        "espace-formateur/abonnements/<int:pk>/",
        formateur_views.formateur_subscription_edit,
        name="formateur_subscription_edit",
    ),
    path(
        "espace-formateur/abonnements/<int:pk>/approuver/",
        formateur_views.formateur_subscription_approve,
        name="formateur_subscription_approve",
    ),
    path(
        "espace-formateur/abonnements/<int:pk>/refuser/",
        formateur_views.formateur_subscription_reject,
        name="formateur_subscription_reject",
    ),
    path(
        "espace-formateur/recap-abonnements/",
        formateur_views.formateur_recap_subscriptions,
        name="formateur_recap_subscriptions",
    ),
    path(
        "espace-formateur/recap-abonnements/export.xlsx",
        formateur_views.formateur_recap_export_all,
        name="formateur_recap_export_all",
    ),
    path(
        "espace-formateur/recap-abonnements/export-<str:month_str>.xlsx",
        formateur_views.formateur_recap_export_month,
        name="formateur_recap_export_month",
    ),
    # --- Espace formateur contenu (sans demandes d’abonnement) ---
    path(
        "espace-formateur-contenu/",
        formateur_views.formateur_contenu_dashboard,
        name="formateur_contenu_dashboard",
    ),
    path(
        "espace-formateur-contenu/categories/",
        formateur_views.formateur_category_list,
        name="formateur_contenu_category_list",
    ),
    path(
        "espace-formateur-contenu/categories/nouvelle/",
        formateur_views.formateur_category_create,
        name="formateur_contenu_category_create",
    ),
    path(
        "espace-formateur-contenu/categories/<int:pk>/modifier/",
        formateur_views.formateur_category_edit,
        name="formateur_contenu_category_edit",
    ),
    path(
        "espace-formateur-contenu/categories/<int:pk>/supprimer/",
        formateur_views.formateur_category_delete,
        name="formateur_contenu_category_delete",
    ),
    path(
        "espace-formateur-contenu/sujets-pdf/",
        formateur_views.formateur_monthly_content_list,
        name="formateur_contenu_monthly_content_list",
    ),
    path(
        "espace-formateur-contenu/sujets-pdf/nouveau/",
        formateur_views.formateur_monthly_content_create,
        name="formateur_contenu_monthly_content_create",
    ),
    path(
        "espace-formateur-contenu/sujets-pdf/<int:pk>/modifier/",
        formateur_views.formateur_monthly_content_edit,
        name="formateur_contenu_monthly_content_edit",
    ),
    path(
        "espace-formateur-contenu/sujets-pdf/<int:pk>/supprimer/",
        formateur_views.formateur_monthly_content_delete,
        name="formateur_contenu_monthly_content_delete",
    ),
    path(
        "espace-formateur-contenu/corrections/",
        formateur_views.formateur_correction_list,
        name="formateur_contenu_correction_list",
    ),
    path(
        "espace-formateur-contenu/corrections/nouvelle/",
        formateur_views.formateur_correction_create,
        name="formateur_contenu_correction_create",
    ),
    path(
        "espace-formateur-contenu/corrections/<int:pk>/modifier/",
        formateur_views.formateur_correction_edit,
        name="formateur_contenu_correction_edit",
    ),
    path(
        "espace-formateur-contenu/corrections/<int:pk>/supprimer/",
        formateur_views.formateur_correction_delete,
        name="formateur_contenu_correction_delete",
    ),
    path(
        "espace-formateur-contenu/examens/",
        formateur_views.formateur_exam_list,
        name="formateur_contenu_exam_list",
    ),
    path(
        "espace-formateur-contenu/examens/nouveau/",
        formateur_views.formateur_exam_create,
        name="formateur_contenu_exam_create",
    ),
    path(
        "espace-formateur-contenu/examens/<int:pk>/modifier/",
        formateur_views.formateur_exam_edit,
        name="formateur_contenu_exam_edit",
    ),
    path(
        "espace-formateur-contenu/examens/<int:pk>/supprimer/",
        formateur_views.formateur_exam_delete,
        name="formateur_contenu_exam_delete",
    ),
    path(
        "espace-formateur-contenu/examens/<int:pk>/export-resultats.xlsx",
        formateur_views.formateur_exam_results_export,
        name="formateur_contenu_exam_results_export",
    ),
    path(
        "espace-formateur-contenu/recap-abonnements/",
        formateur_views.formateur_recap_subscriptions,
        name="formateur_contenu_recap_subscriptions",
    ),
    path(
        "espace-formateur-contenu/recap-abonnements/export.xlsx",
        formateur_views.formateur_recap_export_all,
        name="formateur_contenu_recap_export_all",
    ),
    path(
        "espace-formateur-contenu/recap-abonnements/export-<str:month_str>.xlsx",
        formateur_views.formateur_recap_export_month,
        name="formateur_contenu_recap_export_month",
    ),
]
